# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 08:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('alipayID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('userName', models.TextField()),
                ('qIDs', models.CharField(max_length=500)),
                ('counting', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
