# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=100)),
                ('symptoms', models.TextField()),
                ('diseases', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=100)),
                ('qid', models.IntegerField(verbose_name='questionNO')),
                ('symptoms', models.TextField()),
                ('diseases', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('qpage', models.IntegerField(primary_key=True, serialize=False)),
                ('counting', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='question_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey1.Questionnaire', verbose_name='pageNO'),
        ),
    ]
